name: CI Pipeline

on:
  push:
    branches:
      - feature/am437xv1
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build step
      run: echo "Building project..."

    - name: Test step
      run: echo "Running tests..."
